### ISSUE TITLE
파일 이름 변경이 안 되네요.

### ISSUE THREAD

**Issue by kndol** [Isitea/Comic-Grabber#10]
제이마나에서 다운로드하는데, 오늘 갑자기 문제가 발생했습니다.

다운로드를 누르면 나타나는 버블 메시지에는 폴더 및 파일 이름이 정확히 표시되는데, 다운로드된 파일이 해당 폴더에 복사가 되지 않네요.

크롬의 다운로드 폴더에 ad364528-271f-4fd8-b26e-6acfec70ba1b.zip 이런 식으로 파일이 생깁니다.

그저께까지는 잘 됐었는데, 갑자기 안 되네요. 이유가 뭘까요?

크롬 카나리 브라우저에서 2.1.3 webRequest 버전 사용 중입니다.

**Comment by Isitea** [comment]
카나리가 업데이트되면서 생긴 현상인가요?
확인 후 버전 업데이트하도록 하겠습니다.
이후 진행은 이곳에 알려드리겠습니다.

**Comment by Isitea** [comment]
확인 결과 이상이 없는 것을 확인했습니다.
혹시 크로노 다운로드 매니저( https://chrome.google.com/webstore/detail/chrono-download-manager ) 를 사용하시나요?
https://mangall.kr/comics/2046416#comment_2046543
과거 같은 현상을 알려주신 사용자가 있습니다.
해당 확장은 정상적인 다운로드 기능을 강제로 취소하고, 같은 주소로 다시 다운로드를 시도합니다.
이 과정에서 사용자가 지정한 저장 위치, 저장 이름 등의 정보가 소실되어 나타나는 현상으로 해당 확장에서 조치를 취하지 않으면 동시 사용이 불가능합니다.

해당 이슈는 추가 문의가 없으시다면 2021.05.12 18:00 이후에 종료하겠습니다.

**Comment by kndol** [comment]
다른 다운로드 매니저와 충돌이 있네요. 며칠 전까지는 문제가 없었는데, 해당 확장 프로그램이 5월 7일에 업데이트됐네요. 
확장 프로그램을 끄면 정상적으로 됩니다.
https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj

**Comment by Isitea** [comment]
다른 확장이네요.
소스코드를 한번 살펴보고 업데이트로 수정이 가능하면 시도해보겠습니다.

**Comment by Isitea** [comment]
> 
> 
> 다른 다운로드 매니저와 충돌이 있네요. 며칠 전까지는 문제가 없었는데, 해당 확장 프로그램이 5월 7일에 업데이트됐네요.
> 확장 프로그램을 끄면 정상적으로 됩니다.
> https://chrome.google.com/webstore/detail/image-downloader/cnpniohnfphhjihaiiggeabnkjhpaldj

해당 확장 프로그램을 살펴본 결과, Chrome에서만 지원하며, 모든 확장 프로그램을 통틀어 마지막에 갱신된(설치 및 업데이트) 확장에서 설정한 이름으로 변경되는 API(chrome.downloads.onDeterminingFilename)를 사용하고 있는 것이 확인되었습니다.
이를 막기 위한 조치를 취하면 해당 확장 및 다른 확장의 오작동을 일으킬 수 있으며, 서로 업데이트될 때마다 동일한 현상이 발생합니다.
(현재 확인된 바로는 Image Downloader Continued, Chrono Download Manager) 또한 같은 방식을 사용해 상호 충돌하는 것으로 보입니다)

이에 해당 기능을 무력화하는 업데이트는 작성은 하였으나 정식 버전에는 업데이트하지 않고 Branch를 분리해 두도록 하겠습니다.

또한 해당 확장 제작자에게 다른 방식을 사용하도록 의견을 제시하였습니다.

제보 감사합니다.

해당 이슈는 이틀 뒤인 2021.05.19 10:00 이후에 닫도록 하겠습니다.
