### ISSUE TITLE
제이마나 이용시에 access denied가 뜹니다

### ISSUE THREAD

**Issue by kidyhs** [Isitea/Comic-Grabber#13]
원래 comic-grabber-v2.0.7-chromium.jmana 쓰다가 갑자기 access denied라는 알림창이 잔뜩 뜨면서 로딩 안되는 그림들이 많아서 comic-grabber-v2.1.4-chromium-webRequest로 바꿨는데도 같은 증상이 계속됩니다 ㅠㅠ

다운된 파일은 로딩안된 이미지는 누락되어있구요... 왜이런건가요?

그리고 Run make.ps1 before loading it into the browser except for chromium base version 이거 하는 방법을 모르겠어서 그냥 확장 프로그램에 끌어다놨는데 그러면 안되는건가요..? 항상 잘 쓰고있습니다!

**Comment by Isitea** [comment]
make.ps1 파일은 윈도우즈 파워쉘 파일로 깃허브에서 소스코드를 받아서 직접 사용하시는 분들을 위한 코드 정리 파일입니다.
일반적으로 받아서 사용하실 때는 https://github.com/Isitea/Comic-Grabber/releases/latest 에서 원하시는 압축 파일만 받아서 압축을 풀고 폴더를 지정하여 사용하시면 됩니다.
만약 소스코드를 받아서 쓰실 경우에는 make.ps1을 정상적으로 실행하면 dist 라는 폴더가 생기고 그 안에 다시 chromium, chromium-webRequest, gecko 폴더가 생기는데 이 중에서 chromium-webRequest 폴더를 사용하시면 됩니다.

현재 제가 시험해보니 정상 작동하는 것 같습니다. 다만 서로 다른 사이트 또는 페이지에서 시험했을 수 도 있으니, 다시 설치해보시고 그래도 작동하지 않는다면 오류가 발생하는 페이지 또는 사이트의 주소를 알려주시면 다시 시험해보겠습니다.

**Comment by kidyhs** [comment]
어.. 여전히 엑세스 디나이가 엄청뜨는게 있어요 컴터 바꺼서 해봤는데도 그러네용
예를들면 이런거요 https://www.jmana1.net/bookdetail?bookdetailid=451955
무슨 기준인지는 모르겠어요 보니까 여러번 새로고침하면 엑박 없어지면서 디나이 됐던 그림까지 다운로드가 돼요

**Comment by kidyhs** [comment]
아 이 증상이 특정만화에 생기는게 아니고 단시간에 너무 여러개 받으면 모든 만화에서 이렇게 바뀌네요

**Comment by Isitea** [comment]
단기 트래픽 차단이었군요.
피드백 감사합니다.
해당 이슈는 종료하겠습니다.
