### ISSUE TITLE
2.1.7 파폭 버전 자동이동기능 관련

### ISSUE THREAD

**Issue by KorZenith** [Isitea/Comic-Grabber#19]
자동이동 기능이 정상작동하지 않는것으로 추정됩니다
자동다운로드 후 다음화로 넘어가지 않네요

크롬으로도 확인해봤는데 크롬은 정상적으로 작동하였습니다

**Comment by Isitea** [comment]
> 자동이동 기능이 정상작동하지 않는것으로 추정됩니다
> 자동다운로드 후 다음화로 넘어가지 않네요
> 
> 크롬으로도 확인해봤는데 크롬은 정상적으로 작동하였습니다

개인 사정으로 인해 업데이트가 좀 밀렸습니다.
가능하면 이번 주 안으로 수정하도록 하겠습니다.

**Comment by Isitea** [comment]
수정되었습니다.
제보 감사합니다.

**Comment by KorZenith** [comment]
2.1.8 파이어폭스 문제해결 확인했습니다
감사히 잘 쓰겠습니다
