### ISSUE TITLE
파폭 2.1.7 버전 다운로드 완료 처리 안되는 문제

### ISSUE THREAD

**Issue by ringout** [Isitea/Comic-Grabber#20]
정확히 어느 버전부터인지 모르겠지만

다운로드를 실행해서 실제 파일이 다운로드 완료되었음에도
앱은 "다운로드 시작" 에서  "다운로드 완료" 단계로 넘어가지 않는 문제가 있습니다.
페이지를 새로고침하기 전까지 ui는 계속 다운로드중인 상태로 몇시간이고 지속되기 때문에
자동저장, 자동 페이지 넘김도 동작하지 않아요...

소통창구가 없어져서 이 리포트를 보실지 모르겠지만 일단 작성해봅니다.

**Comment by Isitea** [comment]
개인 사정으로 인해 업데이트가 좀 밀렸습니다.
가능하면 이번 주 안으로 수정하도록 하겠습니다.

**Comment by Isitea** [comment]
> 정확히 어느 버전부터인지 모르겠지만
> 
> 다운로드를 실행해서 실제 파일이 다운로드 완료되었음에도
> 앱은 "다운로드 시작" 에서  "다운로드 완료" 단계로 넘어가지 않는 문제가 있습니다.
> 페이지를 새로고침하기 전까지 ui는 계속 다운로드중인 상태로 몇시간이고 지속되기 때문에
> 자동저장, 자동 페이지 넘김도 동작하지 않아요...
> 
> 소통창구가 없어져서 이 리포트를 보실지 모르겠지만 일단 작성해봅니다.

개인 사정으로 인해 업데이트가 좀 밀렸습니다.
가능하면 이번 주 안으로 수정하도록 하겠습니다.

**Comment by Isitea** [comment]
원인은 Chrome과 Firefox에서 서로 다른 행동을 하는 함수의 사용이었으며,
이를 수정하여 2.1.7에 반영됩니다.

제보 감사합니다.
