### ISSUE TITLE
제이마나에서 다시 막았네요..

### ISSUE THREAD

**Issue by kidyhs** [Isitea/Comic-Grabber#22]
항상 잘 쓰고있습니다 제이마나에서 또 막았는지 이미지가 없음으로 뜨면서 안받아지네요..

**Comment by Isitea** [comment]
확인해보겠습니다.

**Comment by kidyhs** [comment]
감사합니다! 코믹 그래버만큼 만화보기 편하게 해주는게 없어서요.. 받아서 꿀뷰로 봐야지 만화 보는거같아요 ㅠㅠ 고생 많으십니다...

**Comment by Isitea** [comment]
오래 걸려서 죄송합니다. 그리고 오래 기다려주셔서 감사합니다.
이직 후 정신이 없어서 고작 두 줄만 수정하면 되는 걸 미뤘네요.
2022.01.21 19:00 이전에 패치된 버전으로 업로드할 예정입니다.
