### ISSUE TITLE
그토끼 사이트에서

### ISSUE THREAD

**Issue by ringout** [Isitea/Comic-Grabber#25]
2월14일부터
M모 사이트 만화 다운로드 버튼을 누르면
만화 페이지 이미지마다 network error404 문구가 붙은 썸네일들이 화면 우측에 주르륵 뜨면서 
아무 페이지도 다운로드되지 않습니다.

업로드된지 오래된 만화도 마찬가지네요.

+ 브라우저 환경 기재를 누락했는데 파폭 122.0.1 (64-비트) 입니다.
본업으로 바쁘실텐데 계속 신경써주셔서 감사합니다.

**Comment by Isitea** [comment]
확인하고 조치하겠습니다.
감사합니다.

**Comment by eva3357** [comment]
역시 검색을 해야해
찾아서 들어왔는데 대응 시작하고 계셨군요 감사합니다.

**Comment by Isitea** [comment]
확인 결과 해당 사이트에 대해서 일반 버전은 사용이 불가능해졌습니다.
https://github.com/Isitea/Comic-Grabber/releases
에서 Referer 수정 기능이 있는 확장을 사용해주세요.

이 외의 다른 방법으로 대응할 수 있는지에 대해서는 검토 후 적용하겠습니다.

**Comment by eva3357** [comment]
그대로 사용하여 파이어폭스에서도 작동한다면 다행이지만
최초 파이어폭스용을 만들 때는 압축 파일 내의 다운로드가 제대로 작동하지 않았습니다.

현 문제는 Manifest V3 대응과 함께 반영할 예정이므로 주중에는 작업할 시간이 없어 3월 3일까지 기다려주시면 좋겠습니다.

**Comment by ringout** [comment]
안녕하세요. 
생업으로 바쁘신데 재촉하기가 뭐해서 그냥 기다리다가 
최근에 M모사이트 캡챠방식도 바뀐 김에 질문 남겨봅니다.
혹시 파폭용은 이제 가망이 없을까요?

**Comment by Isitea** [comment]
> 안녕하세요. 
> 생업으로 바쁘신데 재촉하기가 뭐해서 그냥 기다리다가 
> 최근에 M모사이트 캡챠방식도 바뀐 김에 질문 남겨봅니다.
> 혹시 파폭용은 이제 가망이 없을까요? 

제가 만화를 안 보게 되서 대응이 느려졌네요. 죄송합니다.

파이어폭스 쪽은 2024.05.15 저녁에 대응이 가능한지 등을 확인하여 전체 버전업을 하거나 아예 제외하거나 결정하여 글 남기겠습니다.

감사합니다.

**Comment by Isitea** [comment]
> 안녕하세요. 생업으로 바쁘신데 재촉하기가 뭐해서 그냥 기다리다가 최근에 M모사이트 캡챠방식도 바뀐 김에 질문 남겨봅니다. 혹시 파폭용은 이제 가망이 없을까요?

2024.05.15 22.41 Firefox 판도 2.1.10 으로 판올림 했습니다.
Add-ons 에 표시되는 것은 시간이 조금 걸릴 것으로 보이며,
업데이트 후에는 Chromium 판과 동일하게 정상 작동합니다.

기다려주셔서 감사합니다.

**Comment by ringout** [comment]
> 2024.05.15 22.41 Firefox 판도 2.1.10 으로 판올림 했습니다. Add-ons 에 표시되는 것은 시간이 조금 걸릴 것으로 보이며, 업데이트 후에는 Chromium 판과 동일하게 정상 작동합니다.
> 
> 기다려주셔서 감사합니다.

개인프로젝트에 부채의식 가지실 필요가 없는데도 리퀘스트 받아주셔서 너무너무 감사합니다.
매번 노고에 감사드립니다!
