### ISSUE TITLE
파일이름 저장 이상하게 되는 이슈

### ISSUE THREAD

**Issue by kidyhs** [Isitea/Comic-Grabber#26]
제작자님 아직 만드신 툴 잘 쓰고있는 이용자입니다 ㅠ 갑자기 마나토끼 다운받으면 파일이름이 4fb779dc-cedc-457f-9372-09204fc27c1b
이런식으로 저장되길래 질문글 올려봅니다

**Comment by kidyhs** [comment]
제 환경 문제였네요; 해결했습니다ㅠㅠ 항상 잘 쓰고있습니다!

**Comment by Isitea** [comment]
> 제 환경 문제였네요; 해결했습니다ㅠㅠ 항상 잘 쓰고있습니다!

안녕하세요, kidyhs님.
개발자 Isitea 입니다.

앞으로도 사용상에 문제가 있다면 편하게 연락주세요.

감사합니다.

**Comment by kidyhs** [comment]
안녕하세요 제작자님 혹시 문의 드릴게 있는데요 옛날에 마나모아에서 쓸때는 본 편수는 회색으로 사이트에서 표시가 됐는데 마나토끼는 로그인을 해야지만 그 기능이 생겨서요.. 무슨 차이일까요? 감사합니다!
